name: GOKHAN_BIST_RADAR_PRO

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Repo indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kütüphaneleri yükle
        run: |
          pip install -r requirements.txt

      - name: Bot çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python telegram_command_bot.py